DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BLOG CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

CREATE TABLE USERS(
	USER_ID NUMBER(10) 		PRIMARY KEY,
	ID VARCHAR2(20) 			NOT NULL,
	PASSWORD VARCHAR2(30) 		NOT NULL,
	USER_NAME VARCHAR2(20) 		NOT NULL,
	ROLE VARCHAR2(20) 		NOT NULL
);

CREATE TABLE BLOG(
	BLOG_ID NUMBER(10) 		PRIMARY KEY NOT NULL, 	
	BLOG_NAME VARCHAR2(30) 	NOT NULL,
	TAG VARCHAR2(500),
	CNT_DISPLAY_POST NUMBER,
	STATUS VARCHAR2(20),
	USER_ID VARCHAR2(20),
	FOREIGN KEY (BLOG_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CATEGORY(
    CATEGORY_ID NUMBER(10) 			PRIMARY KEY NOT NULL,
	CATEGORY_NAME VARCHAR2(50) 		NOT NULL,
	DISPLAY_TYPE VARCHAR2(50) 		NOT NULL,
	CNT_DISPLAY_POST NUMBER		NOT NULL,
    DESCRIPTION VARCHAR2(500),
	BLOG_ID NUMBER(10) 			NOT NULL,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG (BLOG_ID) ON DELETE CASCADE 
);

CREATE TABLE POST(
	POST_ID NUMBER(10) PRIMARY KEY NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000),
	CREATED_DATE DATE DEFAULT SYSDATE,
	CATEGORY_ID NUMBER(10) NOT NULL,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID) ON DELETE CASCADE 
);


INSERT INTO USERS(USER_ID, ID, PASSWORD, USER_NAME, ROLE) VALUES (1, 'admin', '1234', '관리자', 'ADMIN');
INSERT INTO USERS(USER_ID, ID, PASSWORD, USER_NAME, ROLE) VALUES (2, 'user', '1234', '유저', 'USER');

SELECT * FROM USERS;
SELECT * FROM BLOG;
SELECT * FROM CATEGORY;
SELECT * FROM POST;